# Generated by Django 3.2.11 on 2022-02-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('code', models.TextField(unique=True)),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('stripe_id', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
            ],
            options={
                'db_table': 'offers',
            },
            bases=('products.item',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.item')),
                ('uber_eats_id', models.TextField(null=True)),
                ('category', models.TextField()),
                ('facebook_id', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
            bases=('products.item',),
        ),
    ]
